# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Loki installation tasks
  tags:
    - setup-all
    - setup-loki
    - install-all
    - install-loki
  block:
    - name: Validate Loki configuration
      when: loki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Loki
      when: loki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Loki uninstallation tasks
  tags:
    - setup-all
    - setup-loki
  block:
    - name: Uninstall Loki
      when: not loki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
