# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Run Loki installation tasks
  tags:
    - setup-all
    - setup-loki
    - install-all
    - install-loki
  block:
    - when: loki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: loki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Run Loki uninstallation tasks
  tags:
    - setup-all
    - setup-loki
  block:
    - when: not loki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
