---

- name: Fail if required Loki settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - loki_enabled

- name: (Deprecation) Catch and report renamed Loki settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'loki_basic_auth_enabled', 'new': 'loki_container_labels_middleware_basic_auth_enabled'}
    - {'old': 'loki_basic_auth_username', 'new': '<superseded by loki_container_labels_middleware_basic_auth_users>'}
    - {'old': 'loki_basic_auth_password', 'new': '<superseded by loki_container_labels_middleware_basic_auth_users>'}
    - {'old': 'loki_reporting_enabled', 'new': 'loki_analytics_reporting_enabled'}
    - {'old': 'loki_container_common_path_prefix', 'new': 'loki_common_path_prefix'}
    - {'old': 'loki_container_storage_chunks_directory', 'new': 'loki_storage_chunks_directory'}
    - {'old': 'loki_container_storage_rules_directory', 'new': 'loki_storage_rules_directory'}
    - {'old': 'loki_container_http_port', 'new': 'loki_server_http_listen_port'}
    - {'old': 'loki_container_grpc_port', 'new': 'loki_server_grpc_listen_port'}
