---

- name: Fail if required loki settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - loki_enabled

- name: (Deprecation) Catch and report renamed loki settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'loki_basic_auth_enabled', 'new': 'loki_container_labels_metrics_middleware_basic_auth_enabled'}
    - {'old': 'loki_basic_auth_username', 'new': '<superseded by prometheus_ssh_exporter_container_labels_metrics_middleware_basic_auth_users>'}
    - {'old': 'loki_basic_auth_password', 'new': '<superseded by prometheus_ssh_exporter_container_labels_metrics_middleware_basic_auth_users>'}

